### ISSUE TITLE
Hamburger Menu not working

### ISSUE THREAD

**Issue by TigerTJJ** [ChristopherKlay/StadiaEnhanced#224]
I found out that F12 is bound to "screenshot". Delightful.

Anyways, I cannot open this nice hamburger menu I saw in the extension photos.

This is the error posted in the console:

```
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at isLocation (enhanced.js:4176:65)
    at enhanced.js:3251:9
```

Said line number:
           ` return document.querySelector('.X1asv.ahEBEd.LJni0').style.opacity != '0'`

I believe Stadia has changed some css class tags. I thought this problem was because I installed this on Microsoft Edge, but it's the same on Chrome.

_Note: I am running Pi-Hole on this network, which would block ads and trackers, but after allowing a whitelist, I did not see any changes._

**Comment by TigerTJJ** [comment]
It's fixed! Thanks.
